"use client";

import { ArrowRight, Building2, CalendarClock, Calculator as CalculatorIcon, Check, Download, Factory, Home as HomeIcon, Leaf, MessageCircle, ShieldCheck, Sparkles, Star } from "lucide-react";
import { LanguageSwitcher } from "./language-switcher";
import { useLanguage } from "./language-context";
import { PricingCalculator } from "./pricing-calculator";
import { RevealController } from "./reveal-controller";
import { WhatsAppContact } from "./whatsapp-contact";

const copy = {
  en: {
    nav:["Services","Pricing","About","Get a quote"], eyebrow:"Serving Guwahati & North East India", hero:["Cleaner spaces.","Better days.","Professional housekeeping for homes and businesses, delivered by trained teams with modern equipment and a sharp eye for detail.","Book on WhatsApp","Calculate my price","Explore services"], trust:[["Trained","professionals"],["Eco-friendly","cleaning products"],["Flexible","service plans"]], marquee:["Homes","Offices","Hotels","Hospitals","Industrial","Institutions"], servicesKicker:"What we clean", servicesTitle:["One team. Every kind","of clean."], servicesLead:"From everyday upkeep to intensive deep cleaning, we bring the right people, products and equipment for the job.", services:[
      ["Residential cleaning","Deep cleaning for apartments, villas and homes — from kitchens and bathrooms to sofas, carpets and windows.",["Full-home deep cleaning","Move-in & move-out","Kitchen & bathroom care"]],
      ["Commercial housekeeping","Reliable daily and periodic cleaning for offices, hotels, hospitals, schools, banks, malls and retail stores.",["Office housekeeping","Washroom maintenance","Common area upkeep"]],
      ["Industrial & specialist","Equipment-led cleaning for demanding sites, floors and facilities across Assam and North East India.",["Machine floor scrubbing","Marble polishing","Post-construction cleaning"]],
    ], request:"Request on WhatsApp", qualityKicker:"The CleanMate standard", qualityTitle:["Clean isn’t a look.","It’s a feeling."], qualityLead:"A healthier home. A sharper workplace. A space you’re proud to walk into. That’s what our trained professionals work toward on every visit.", qualityImage:["Assam-born.","Service-driven."], reasons:[["Verified professionals","Experienced, trained staff you can feel comfortable welcoming into your space."],["Eco-conscious products","Effective cleaning products selected with people, surfaces and the environment in mind."],["Modern equipment","Professional machines and proven methods for a consistently higher-quality finish."],["Quality assured","Careful supervision, timely delivery and a customer-satisfaction-first approach."]], chat:"Chat on WhatsApp", pricingKicker:"Clear starting prices", pricingTitle:["Professional clean.","Straightforward price."], pricingLead:"Every space is different. These starting prices help you plan; we’ll confirm your quote based on size, condition, location and service frequency.", quote:"Get a WhatsApp quote", table:["Popular home services","Starting at"], priceNames:["Deep Cleaning · 1 BHK","Deep Cleaning · 2 BHK","Deep Cleaning · 3 BHK","Deep Cleaning · 4 BHK","Bathroom Deep Clean","Kitchen Deep Clean","Sofa Cleaning · 5 seater","Mattress Cleaning"], priceNote:"Commercial services start from ₹3–8 per sq. ft. Terms vary by site and requirement.", industriesKicker:"Built for every space", industriesTitle:["Homes to hospitals,","we’re ready."], industries:["Apartments & villas","Offices & corporate","Hotels & restaurants","Hospitals & schools","Retail & malls","Factories & warehouses"], covered:"Covered", contactKicker:"Ready when you are", contactTitle:["Let’s make your space","feel new again."], footer:["Professional housekeeping & facility management","Guwahati · Assam · North East India"], whatsapp:"Hi CleanMate, I'd like to book a cleaning service.", trusted:"Trusted locally", badge:["Professional care,","every single visit."],
  },
  hi: {
    nav:["सेवाएँ","मूल्य","हमारे बारे में","कोटेशन पाएँ"], eyebrow:"गुवाहाटी और पूर्वोत्तर भारत में सेवा", hero:["स्वच्छ जगहें।","बेहतर दिन।","घरों और व्यवसायों के लिए प्रशिक्षित टीम, आधुनिक उपकरण और बारीकी से की गई पेशेवर सफाई।","WhatsApp पर बुक करें","कीमत जानें","सेवाएँ देखें"], trust:[["प्रशिक्षित","पेशेवर"],["पर्यावरण-अनुकूल","सफाई उत्पाद"],["लचीली","सेवा योजनाएँ"]], marquee:["घर","ऑफिस","होटल","अस्पताल","औद्योगिक","संस्थान"], servicesKicker:"हम क्या साफ करते हैं", servicesTitle:["एक टीम। हर तरह की","सफाई।"], servicesLead:"नियमित देखभाल से गहरी सफाई तक, हम सही लोग, उत्पाद और उपकरण लेकर आते हैं।", services:[
      ["घरेलू सफाई","अपार्टमेंट, विला और घरों की गहरी सफाई — रसोई और बाथरूम से लेकर सोफा, कालीन और खिड़कियों तक।",["पूरे घर की गहरी सफाई","मूव-इन और मूव-आउट","रसोई और बाथरूम देखभाल"]],
      ["व्यावसायिक हाउसकीपिंग","ऑफिस, होटल, अस्पताल, स्कूल, बैंक, मॉल और दुकानों के लिए भरोसेमंद सफाई।",["ऑफिस हाउसकीपिंग","वॉशरूम रखरखाव","साझा क्षेत्रों की देखभाल"]],
      ["औद्योगिक और विशेष","असम और पूर्वोत्तर भारत में कठिन स्थानों और सुविधाओं के लिए मशीन-आधारित सफाई।",["मशीन से फर्श सफाई","मार्बल पॉलिशिंग","निर्माण के बाद सफाई"]],
    ], request:"WhatsApp पर अनुरोध करें", qualityKicker:"CleanMate का मानक", qualityTitle:["सफाई केवल दिखती नहीं।","महसूस होती है।"], qualityLead:"स्वस्थ घर, बेहतर कार्यस्थल और ऐसी जगह जिस पर आपको गर्व हो। हर सेवा में हमारी टीम यही लक्ष्य रखती है।", qualityImage:["असम में जन्मा।","सेवा के लिए समर्पित।"], reasons:[["सत्यापित पेशेवर","अनुभवी और प्रशिक्षित कर्मचारी जिनका आप भरोसे से स्वागत कर सकते हैं।"],["पर्यावरण-सचेत उत्पाद","लोगों, सतहों और पर्यावरण को ध्यान में रखकर चुने गए प्रभावी उत्पाद।"],["आधुनिक उपकरण","लगातार बेहतर परिणाम के लिए पेशेवर मशीनें और सिद्ध तरीके।"],["गुणवत्ता सुनिश्चित","सावधानीपूर्ण निगरानी, समय पर सेवा और ग्राहक संतुष्टि।"]], chat:"WhatsApp पर बात करें", pricingKicker:"स्पष्ट शुरुआती कीमतें", pricingTitle:["पेशेवर सफाई।","सीधी कीमत।"], pricingLead:"हर जगह अलग होती है। ये शुरुआती कीमतें योजना बनाने में मदद करती हैं; अंतिम कोटेशन आकार, स्थिति और सेवा पर निर्भर होगा।", quote:"WhatsApp कोटेशन पाएँ", table:["लोकप्रिय घरेलू सेवाएँ","शुरुआती कीमत"], priceNames:["गहरी सफाई · 1 BHK","गहरी सफाई · 2 BHK","गहरी सफाई · 3 BHK","गहरी सफाई · 4 BHK","बाथरूम गहरी सफाई","रसोई गहरी सफाई","सोफा सफाई · 5 सीटर","गद्दे की सफाई"], priceNote:"व्यावसायिक सेवाएँ ₹3–8 प्रति वर्ग फुट से शुरू होती हैं। शर्तें स्थान और आवश्यकता पर निर्भर हैं।", industriesKicker:"हर जगह के लिए तैयार", industriesTitle:["घर से अस्पताल तक,","हम तैयार हैं।"], industries:["अपार्टमेंट और विला","ऑफिस और कॉर्पोरेट","होटल और रेस्तराँ","अस्पताल और स्कूल","रिटेल और मॉल","फैक्ट्री और गोदाम"], covered:"उपलब्ध", contactKicker:"जब आप तैयार हों", contactTitle:["आइए आपकी जगह को","फिर नया बनाएँ।"], footer:["पेशेवर हाउसकीपिंग और सुविधा प्रबंधन","गुवाहाटी · असम · पूर्वोत्तर भारत"], whatsapp:"नमस्ते CleanMate, मैं सफाई सेवा बुक करना चाहता/चाहती हूँ।", trusted:"स्थानीय भरोसा", badge:["हर बार पेशेवर", "देखभाल।"],
  },
  as: {
    nav:["সেৱাসমূহ","মূল্য","আমাৰ বিষয়ে","মূল্য জানক"], eyebrow:"গুৱাহাটী আৰু উত্তৰ-পূব ভাৰতত সেৱা", hero:["পৰিষ্কাৰ ঠাই।","সুন্দৰ দিন।","ঘৰ আৰু ব্যৱসায়ৰ বাবে প্ৰশিক্ষিত দল, আধুনিক সঁজুলি আৰু সূক্ষ্ম যত্নৰে পেছাদাৰী পৰিষ্কাৰ সেৱা।","WhatsApp-ত বুক কৰক","মূল্য গণনা কৰক","সেৱা চাওক"], trust:[["প্ৰশিক্ষিত","পেছাদাৰী"],["পৰিৱেশ-বান্ধৱ","পৰিষ্কাৰ সামগ্ৰী"],["সুবিধাজনক","সেৱা পৰিকল্পনা"]], marquee:["ঘৰ","কাৰ্যালয়","হোটেল","চিকিৎসালয়","ঔদ্যোগিক","প্ৰতিষ্ঠান"], servicesKicker:"আমি কি পৰিষ্কাৰ কৰোঁ", servicesTitle:["এটা দল। সকলো ধৰণৰ","পৰিষ্কাৰ।"], servicesLead:"দৈনন্দিন যত্নৰ পৰা গভীৰ পৰিষ্কাৰলৈ, আমি উপযুক্ত মানুহ, সামগ্ৰী আৰু সঁজুলি লৈ আহোঁ।", services:[
      ["ঘৰুৱা পৰিষ্কাৰ","এপাৰ্টমেণ্ট, ভিলা আৰু ঘৰৰ গভীৰ পৰিষ্কাৰ — পাকঘৰ আৰু স্নানাগাৰৰ পৰা ছোফা, কাৰ্পেট আৰু খিৰিকীলৈ।",["সম্পূৰ্ণ ঘৰৰ গভীৰ পৰিষ্কাৰ","মুভ-ইন আৰু মুভ-আউট","পাকঘৰ আৰু স্নানাগাৰ যত্ন"]],
      ["বাণিজ্যিক হাউচকীপিং","কাৰ্যালয়, হোটেল, চিকিৎসালয়, বিদ্যালয়, বেংক, মল আৰু দোকানৰ বাবে নিৰ্ভৰযোগ্য সেৱা।",["কাৰ্যালয় হাউচকীপিং","শৌচাগাৰ ৰক্ষণাবেক্ষণ","সাধাৰণ এলেকাৰ যত্ন"]],
      ["ঔদ্যোগিক আৰু বিশেষ","অসম আৰু উত্তৰ-পূব ভাৰতৰ কঠিন স্থান আৰু সুবিধাৰ বাবে যন্ত্ৰ-চালিত পৰিষ্কাৰ।",["যন্ত্ৰেৰে মজিয়া পৰিষ্কাৰ","মাৰ্বল পলিচিং","নিৰ্মাণৰ পিছৰ পৰিষ্কাৰ"]],
    ], request:"WhatsApp-ত অনুৰোধ কৰক", qualityKicker:"CleanMate-ৰ মানদণ্ড", qualityTitle:["পৰিষ্কাৰ কেৱল দেখা নহয়।","ই অনুভৱ হয়।"], qualityLead:"স্বাস্থ্যকৰ ঘৰ, সুন্দৰ কৰ্মস্থলী আৰু গৌৰৱৰ ঠাই। প্ৰতিটো সেৱাত আমাৰ দলৰ এয়াই লক্ষ্য।", qualityImage:["অসমত জন্ম।","সেৱাত সমৰ্পিত।"], reasons:[["যাচাইকৃত পেছাদাৰী","অভিজ্ঞ আৰু প্ৰশিক্ষিত কৰ্মচাৰী যাক আপুনি বিশ্বাস কৰিব পাৰে।"],["পৰিৱেশ-সচেতন সামগ্ৰী","মানুহ, পৃষ্ঠ আৰু পৰিৱেশৰ কথা ভাবি বাছনি কৰা কাৰ্যকৰী সামগ্ৰী।"],["আধুনিক সঁজুলি","ধাৰাবাহিক উন্নত ফলাফলৰ বাবে পেছাদাৰী যন্ত্ৰ আৰু প্ৰমাণিত পদ্ধতি।"],["গুণগত মান নিশ্চিত","সাৱধান তত্বাৱধান, সময়মতে সেৱা আৰু গ্ৰাহক সন্তুষ্টি।"]], chat:"WhatsApp-ত কথা পাতক", pricingKicker:"স্পষ্ট আৰম্ভণি মূল্য", pricingTitle:["পেছাদাৰী পৰিষ্কাৰ।","সহজ মূল্য।"], pricingLead:"প্ৰতিটো ঠাই বেলেগ। এই আৰম্ভণি মূল্যই পৰিকল্পনাত সহায় কৰে; চূড়ান্ত মূল্য আকাৰ, অৱস্থা আৰু সেৱাৰ ওপৰত নিৰ্ভৰ কৰিব।", quote:"WhatsApp মূল্য জানক", table:["জনপ্ৰিয় ঘৰুৱা সেৱা","আৰম্ভণি মূল্য"], priceNames:["গভীৰ পৰিষ্কাৰ · 1 BHK","গভীৰ পৰিষ্কাৰ · 2 BHK","গভীৰ পৰিষ্কাৰ · 3 BHK","গভীৰ পৰিষ্কাৰ · 4 BHK","স্নানাগাৰ গভীৰ পৰিষ্কাৰ","পাকঘৰ গভীৰ পৰিষ্কাৰ","ছোফা পৰিষ্কাৰ · 5 আসন","গাদি পৰিষ্কাৰ"], priceNote:"বাণিজ্যিক সেৱা প্ৰতি বৰ্গফুট ₹3–8ৰ পৰা আৰম্ভ হয়। চৰ্ত স্থান আৰু প্ৰয়োজন অনুসৰি।", industriesKicker:"প্ৰতিটো ঠাইৰ বাবে", industriesTitle:["ঘৰৰ পৰা চিকিৎসালয়লৈ,","আমি সাজু।"], industries:["এপাৰ্টমেণ্ট আৰু ভিলা","কাৰ্যালয় আৰু কৰ্পোৰেট","হোটেল আৰু ৰেষ্টুৰেণ্ট","চিকিৎসালয় আৰু বিদ্যালয়","ৰিটেইল আৰু মল","কাৰখানা আৰু গুদাম"], covered:"উপলব্ধ", contactKicker:"আপুনি সাজু হ’লে", contactTitle:["আহক আপোনাৰ ঠাইক","পুনৰ নতুন কৰোঁ।"], footer:["পেছাদাৰী হাউচকীপিং আৰু সুবিধা ব্যৱস্থাপনা","গুৱাহাটী · অসম · উত্তৰ-পূব ভাৰত"], whatsapp:"নমস্কাৰ CleanMate, মই পৰিষ্কাৰ সেৱা বুক কৰিব বিচাৰোঁ।", trusted:"স্থানীয় বিশ্বাস", badge:["প্ৰতিবাৰ পেছাদাৰী", "যত্ন।"],
  },
} as const;

const prices = ["₹2,500","₹3,500","₹4,500","₹5,500","₹600 / bathroom","₹1,200","₹1,200","₹700"];
const serviceIcons = [HomeIcon, Building2, Factory];
const reasonIcons = [ShieldCheck, Leaf, Sparkles, Star];
const brochureLabels = { en: "Download brochure", hi: "ब्रोशर डाउनलोड करें", as: "ব্ৰ’চাৰ ডাউনলোড কৰক" } as const;

export default function Home() {
  const { language } = useLanguage();
  const t = copy[language];
  const whatsappUrl = (message = t.whatsapp) => `https://wa.me/919774883172?text=${encodeURIComponent(message)}`;
  return <main><RevealController/>
    <header className="nav-wrap"><a className="brand" href="#top"><span className="brand-mark"><Sparkles size={19}/></span><span>Clean<span>mate.</span></span></a><nav><a href="#services">{t.nav[0]}</a><a href="#pricing">{t.nav[1]}</a><a href="#about">{t.nav[2]}</a></nav><div className="nav-actions"><LanguageSwitcher/><a className="button button-dark nav-cta" href={whatsappUrl()} target="_blank" rel="noreferrer"><MessageCircle size={16}/> {t.nav[3]}</a></div></header>
    <section className="hero" id="top"><div className="hero-copy"><div className="eyebrow"><span/> {t.eyebrow}</div><h1>{t.hero[0]}<br/><em>{t.hero[1]}</em></h1><p>{t.hero[2]}</p><div className="hero-actions"><a className="button button-green" href={whatsappUrl()} target="_blank" rel="noreferrer">{t.hero[3]} <MessageCircle size={18}/></a><div className="hero-links"><a className="button button-calculator" href="#calculator"><CalculatorIcon size={17}/> {t.hero[4]}</a><a className="text-link" href="#services">{t.hero[5]} <ArrowRight size={15}/></a></div></div><div className="trust-row">{[[ShieldCheck,t.trust[0]],[Leaf,t.trust[1]],[CalendarClock,t.trust[2]]].map(([Icon,item])=>{const I=Icon as typeof ShieldCheck; const words=item as readonly string[]; return <div className="trust-item" key={words[0]}><span className="trust-icon"><I size={19}/></span><span className="trust-copy"><b>{words[0]}</b><small>{words[1]}</small></span></div>})}</div></div><div className="hero-visual"><img src="/cleanmate-team.png" alt="CleanMate professional cleaning team member"/><div className="hero-badge"><span><Star size={15} fill="currentColor"/> {t.trusted}</span><b>{t.badge[0]}<br/>{t.badge[1]}</b></div></div></section>
    <section className="marquee">{t.marquee.map((item,index)=><span key={item}>{index>0&&<i>✦</i>}{item}</span>)}</section>
    <section className="section services-section" id="services"><div className="section-heading"><div><p className="kicker">{t.servicesKicker}</p><h2>{t.servicesTitle[0]}<br/>{t.servicesTitle[1]}</h2></div><p>{t.servicesLead}</p></div><div className="service-grid">{t.services.map(([title,text,list],i)=>{const Icon=serviceIcons[i]; return <article className="service-card" key={title}><span className="card-number">0{i+1}</span><div className="service-icon"><Icon/></div><h3>{title}</h3><p>{text}</p><ul>{list.map(item=><li key={item}><Check size={15}/>{item}</li>)}</ul><a href={whatsappUrl(`${t.whatsapp} ${title}`)} target="_blank" rel="noreferrer">{t.request} <ArrowRight size={16}/></a></article>})}</div></section>
    <section className="quality" id="about"><div className="quality-copy"><div className="quality-main"><p className="kicker light">{t.qualityKicker}</p><h2>{t.qualityTitle[0]}<br/>{t.qualityTitle[1]}</h2><p className="lead">{t.qualityLead}</p><div className="quality-actions"><a className="button button-light" href={whatsappUrl()} target="_blank" rel="noreferrer">{t.chat} <MessageCircle size={17}/></a><a className="button button-download" href="/cleanmate-services-pricing.pdf" download="CleanMate-Services-and-Pricing.pdf">{brochureLabels[language]} <Download size={17}/></a></div></div><div className="reason-grid">{t.reasons.map(([title,desc],i)=>{const Icon=reasonIcons[i]; return <div className="reason" key={title}><Icon/><div><h3>{title}</h3><p>{desc}</p></div></div>})}</div></div></section>
    <section className="section pricing" id="pricing"><div className="price-intro"><p className="kicker">{t.pricingKicker}</p><h2>{t.pricingTitle[0]}<br/>{t.pricingTitle[1]}</h2><p>{t.pricingLead}</p><a href={whatsappUrl()} target="_blank" rel="noreferrer" className="button button-dark">{t.quote} <MessageCircle size={17}/></a></div><div className="price-card"><div className="price-head"><span>{t.table[0]}</span><span>{t.table[1]}</span></div>{t.priceNames.map((name,i)=><div className="price-row" key={name}><span>{name}</span><b>{prices[i]}</b></div>)}<p className="price-note">{t.priceNote}</p></div></section>
    <section className="industries"><p className="kicker">{t.industriesKicker}</p><h2>{t.industriesTitle[0]}<br/>{t.industriesTitle[1]}</h2><div className="industry-list">{t.industries.map((item,i)=><div key={item}><span className="industry-number">0{i+1}</span><strong>{item}</strong><span className="industry-status"><Check size={14}/> {t.covered}</span></div>)}</div></section>
    <PricingCalculator language={language}/>
    <section className="contact" id="contact"><div><p className="kicker light">{t.contactKicker}</p><h2>{t.contactTitle[0]}<br/>{t.contactTitle[1]}</h2></div><WhatsAppContact language={language}/></section>
    <footer><a className="brand footer-brand" href="#top"><span className="brand-mark"><Sparkles size={19}/></span><span>Clean<span>mate.</span></span></a><p>{t.footer[0]}</p><p>{t.footer[1]}</p></footer>
  </main>;
}
